SELECT 
	c.CUSTOMER_ID AS 'ID do Customer',
	NAME AS 'Nome do Customer',
	COALESCE(SUM(ORDER_QTY * PRICE), 0) AS 'Preco do Produto'
FROM CUSTOMER c 
LEFT JOIN CUSTOMER_ORDER co ON co.CUSTOMER_ID = c.CUSTOMER_ID 
LEFT JOIN PRODUCT p ON p.PRODUCT_ID = co.PRODUCT_ID 
GROUP BY 1, 2;
	