SELECT 
	CUSTOMER.CUSTOMER_ID AS 'ID do CUSTOMER',
	NAME AS 'Nome',
	SUM(ORDER_QTY * PRICE) AS 'Preco'
FROM CUSTOMER_ORDER
INNER JOIN CUSTOMER ON CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID 
INNER JOIN PRODUCT ON CUSTOMER_ORDER.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY 1, 2;