SELECT
	ORDER_ID,
	CUSTOMER.CUSTOMER_ID,
	ORDER_DATE,
	SHIP_DATE,
	NAME, 
	STREET_ADDRESS,
	CITY,
	STATE,
	ZIP,
	PRODUCT_ID,
	ORDER_QTY
FROM
	CUSTOMER
INNER JOIN CUSTOMER_ORDER ON CUSTOMER_ORDER.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID;