CREATE TABLE COMPANY (
	COMPANY_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(255),
	DESCRIPTION TEXT,
	PRIMARY_CONTACT_ATTENDEE_ID INTEGER,
	
	FOREIGN KEY (PRIMARY_CONTACT_ATTENDEE_ID)
	REFERENCES ATTENDEE (ATTENDEE_ID)
);