CREATE TABLE PRESENTATION_ATTENDANCE(
	TICKET_ID SERIAL PRIMARY KEY,
	PRESENTATION_ID INTEGER NOT NULL REFERENCES PRESENTATION(PRESENTATION_ID),
	ATTENDEE_ID INTEGER NOT NULL REFERENCES ATTENDEE(ATTENDEE_ID)
);